### ISSUE TITLE
Responsive Size

### ISSUE THREAD

**Issue by robrez** [RenatoUtsch/poly-nvd3#1]
I just started playing with your components last night. Let me say, well done.. I applaud your work.

It looks like attributes for height and width must be explicitly provided. I was wondering what your take may be on how to implement a responsively sized chart.

I'm currently binding height/width using an approach that is something like this...

```
  <nvd3-line-chart height="{{chartHeight}}" width="{{chartWidth}}"></nvd3-line-chart>
```

```
domReady: function() {
    this.chartHeight = this.offsetHeight * .8;
    this.chartWidth = this.offsetWidth *.8;
}
```

I was thinking of using the resizable mixin, recalculating values. I'm also new to nvd3 and am unsure if there is a built-in mechanism that would be more appropriate than my approach.

I did find this example: [lineChartSVGResize.html](https://github.com/novus/nvd3/blob/master/examples/lineChartSVGResize.html)

It looks like nv.utils.windowResize could do the trick if I were able to provide some sort of configuration (simple attribute or callback function) to nvd3-abstract-chart

**Comment by RenatoUtsch** [comment]
Hey, thanks for using poly-nvd3!

If you didn't, take a look at the development branch. The charts now takes the maximum available space if you don't specify width and height. For example, in the [nvd3-line-chart example](https://github.com/RenatoUtsch/poly-nvd3/blob/development/nvd3-line-chart/demo.html), the first line chart takes a width of at most of 800px, because that is the size of the parent div.

Also, notice that the second line chart resizes with the page. If you resize your screen the chart will also resize.

I am just waiting the next nvd3 release (and helping them fix some bugs) before making a new release, but if you have any problems using the development branch just tell me and I'll help you. You will probably have to use the development branch of nvd3 too (it is almost ready for a new release, so it's stable).

**Comment by robrez** [comment]
> The charts now takes the maximum available space if you don't specify width and height.

Thanks, that sounds perfect.. I'll try check it out.
